### ISSUE TITLE
Later versions of Supermon Changed where the AUTOSKY/warnings.txt is looking

### ISSUE THREAD

**Issue by mjwgeek** [Mason10198/SkywarnPlus#76] opened 2024-02-03 18:09 UTC
Check this out, I have an older version of Supermon and the latest 7.4.  They changed where the warnings.txt file is pointed to.  Check out these two versions.  Can you update the config.yaml to point to both just in case, or write to both?  Your choice.  

From older Supermon's link.php file:

// ADDED WA3DSP Autosky warning messages
// if they exist
if (file_exists("/tmp/AUTOSKY/warnings.txt")) {
    if (filesize("/tmp/AUTOSKY/warnings.txt")) {
        $warnings = file_get_contents ("/tmp/AUTOSKY/warnings.txt");
        print "<span style=\"color: red;\"><br><b>$warnings</b></span>";
    }
}
// END WA3DSP

vs 7.4's link.php

if (file_exists("/var/www/html/AUTOSKY/warnings.txt")) {
    if (filesize("/var/www/html/AUTOSKY/warnings.txt")) {
        $warnings = file_get_contents ("/var/www/html/AUTOSKY/warnings.txt");
        print "<span style=\"color: red;\"><br><b>$warnings</b></span>";
    }
}

print "</p>";

Not really a bug it is an issue caused by outside sources. 
Thanks!

**Comment by k5map** [comment] 2024-02-03 22:25
@mjwgeek ... Much thanks for this post as I have confirmed with Supermon v7.4 on ASL, it is also looking for the warnings.txt file in the path /var/www/html/AUTOSKY instead of /tmp/AUTOSKY.  On my HamVoIP nodes, the warnings show up on the Supermon page but on my ASL nodes, they do not (because Supermon is not expecting the file in the /tmp/AUTOSKY directory).

For now, I'm going to modify the Supermon php file until a solution is identified.

**Comment by Mason10198** [comment] 2024-02-03 22:28
This is resolved by simply writing to whichever `warnings.txt` exists in `v0.6.0`, which will be released as soon as testing is complete

**Comment by k5map** [comment] 2024-02-03 22:30
@Mason10198 ... that's great news.  In that case I'll hold off making any changes to my ASL nodes.

**Comment by Mason10198** [comment] 2024-02-04 20:47
Resolved in `v0.6.0`

**Closed as completed by Mason10198** 2024-02-04 20:47 UTC
Labels: bug
